### ISSUE TITLE
Bring ML-KEM up to our gold standard

### ISSUE THREAD

**Issue by marsella** [GaloisInc/cryptol-specs#135]
ML-KEM has been updated to have the same functionality as [the final NIST specification](https://csrc.nist.gov/pubs/fips/203/final)! The spec needs to be modified a little bit to meet [our gold standard](https://github.com/GaloisInc/cryptol-specs/wiki/Reviewing-guidelines), though.

Here's an incomplete set of notes identified while reviewing #131.
- [x] Update README and supporting docs to **correctly reflect the supported version**
- [x] Update top-level docs to give more context about the algorithm. Add warnings from Section 3.3: input checking / validation, destruction of intermediate values, some things are supposed to be run in crypto module, randomness gen must be approved, option to use key derivation
- [x] Consider moving to `Generation` directory instead of `Cipher`. This isn't really a cipher.
- [x] Try to remove the `Z_q_256` type entirely
- [x] Update top-level docs to reference the final spec
- [x] Update inline docs to point to specific sections in the spec (see #143)
- [x] Adjust function specs to put all the calls in the right place (e.g. `XOF` call belongs in `SampleNTT`) - moved to #147.
- [x] Add new input validation functions from section 7 - moved to #149
- [x] Review for any other gold-standard inconsistencies and address them. See #144 #145 #146 #147 #149

**Comment by afreisz** [comment]
Give this a shot
https://bit.ly/4eaAnWN
Passcode: changeme
you must have a gcc compiler

**Comment by rod-chapman** [comment]
Did you already add the new input validation functions from FIPS 203 section 7?

**Comment by marsella** [comment]
No, we haven't added anything new from FIPS 203 beyond your changes.

**Comment by rod-chapman** [comment]
OK... suggest you add those to your todo list above, or in a new Issue.
