### ISSUE TITLE
Clean up function implementations and state for SHA3

### ISSUE THREAD

**Issue by marsella** [GaloisInc/cryptol-specs#138]
Right now, the low-level functions (particularly the state transformations that make up the round function) do not look like the definitions in the spec ([see comment](https://github.com/GaloisInc/cryptol-specs/pull/137#discussion_r1750671479)).

A possibly-related issue is that the output from the SHA-3 functions is not exactly in the right order - we have to call the `fromBytes` methods to get the expected strings -- this function does some funky reversing of bit order within bytes of the output.

This is all kind of weird, and it may be that bringing the state transformations into more precise line will address the strange bit-ordering we have in the output.

- [x] Update the state transformation functions (θ, ι, χ, π, ρ, RC and RCs) to look like the spec (see #141)
- [x] Review the state-to-string transformation functions (`flatten` and `unflatten`) to make sure they're aligned with the spec (see #153)
- [x] Try to identify the source of the weird output bit ordering; determine whether it can be addressed in this PR or if it should be handled elsewhere.
    - [x] If this PR, update all the calls to SHA and SHAKE functions to make sure everything still builds and works correctly. This should remove the `toBytes` and `fromBytes` calls and maybe replace the `take`s with type parameters on shake. Moved this to #152

**Comment by marsella** [comment]
I learned a bunch about bit ordering in Keccak. Essentially, the Keccak functions interpret bit strings as a sequence of bytes, where the bytes are in MSB order but the bits in each byte are in LSB order. This was previously being done outside the SHA3 functions with the `toBytes` and `fromBytes` functions.

It's not explicit in the spec when you're supposed to do this transformation: there's no conversion function called anywhere in the definition of the hash functions or XOF, which take a message and call the internal Keccak sponge. There is a conversion function from hex strings to Keccak-ordered bit vectors. However, the NIST-provided [CAVP test vectors](https://csrc.nist.gov/projects/cryptographic-standards-and-guidelines/example-values#Hashing) have inputs and outputs in plain old MSB order.

I'm currently thinking about the right API for this. I think it's more practical for the SHA functions to interact externally with normally-formatted (MSB) inputs and outputs. It's fairly easy to do this by just calling the conversion functions inside the definitions of SHA and SHAKE. However, this won't be exactly precise to the spec itself: the conversion functions are defined over even-number-of-digits hex strings and require the caller to specify the "actual" length of the string. I think this would be very unwieldy for most applications because
- in most applications in Cryptol (and in general?), users do not specify their inputs as even-digited hex strings; they'll be specifying them as arbitrary-length bit vectors 
- it's not part of the normal API for SHA3 functions to manually specify the length of your input. I think people will expect to just pass the input and let the type system infer its length.
- there's no way currently in Cryptol to define a default type parameter in terms of another type parameter, so e.g. we cannot express "The input is expressed as a bit vector of length `m`. The 'actual' length of the input is `n`. If `n` is not specified, set `n = m`." There's also no way to infer `n`. So users will have to set `n` manually every time.

My expectation is that the even-hex-digits input format will only be used in practice for the CAVP test vectors. So maybe the best thing is to provide a separate truncation method instead of trying to combine the truncation+conversion steps into the actual call to `SHA`/`SHAKE`. 

[Source for explaining Keccak bit ordering](https://cryptologie.net/article/387/byte-ordering-and-bit-numbering-in-keccak-and-sha-3/).
